config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'tasks#index'
  resources :tasks, only: %i[index create update destroy]

  resources :active_tasks, only: %i[index update]

  resources :completed_tasks, only: %i[index new update]

  resources :todos, only: %i[index]

  namespace :api do
    namespace :v1 do
      resources :tasks, only: %i[index create update destroy]

      resources :active_tasks, only: %i[index update]

      resources :completed_tasks, only: %i[index new update]
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  include RailsSortable::Model

  belongs_to :user

  set_sortable :sort
  enum status: %i[active completed]
  scope :by_status, ->(status) { where(status: status) if status.present? }

  before_update :disable_edit_on_completed

  validates :title, presence: true
  validates :completed_to, presence: true
  validate :future_completed_date

  private

  def disable_edit_on_completed
    raise ActiveRecord::Rollback if !status_changed? && completed?
  end

  def future_completed_date
    errors.add(:completed_to, "can't be in the future") if completed_to && completed_to < Date.today
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :tasks
end

app/controllers/active_task_controller.rb
class ActiveTaskController < ApplicationController
  def index
    Task.completed.update_all(status: 0, completed_at: nil)
    @tasks = Task.all.order(:sort)
    respond_to do |format|
      format.js
    end
  end

  def update
    task.update_attributes(status: 0, completed_at: nil)
  end

  private

  def task
    Task.find(params[:id])
  end
end

app/controllers/active_tasks_controller.rb
# frozen_string_literal: true

class ActiveTasksController < ApplicationController
  def index
    current_user.tasks.completed.update_all(status: 0, completed_at: nil)
    @tasks = current_user.tasks.order(:sort)
    respond_to do |format|
      format.js
    end
  end

  def update
    task.update_attributes(status: 0, completed_at: nil)
  end
end

app/controllers/api/react_app_controller.rb
# frozen_string_literal: true

class Api::ReactAppController < ApplicationController
  layout 'react_app'
  skip_before_action :verify_authenticity_token
end

app/controllers/api/v1/active_tasks_controller.rb
# frozen_string_literal: true

class Api::V1::ActiveTasksController < Api::ReactAppController
  def index
    current_user.tasks.completed.update_all(status: 0, completed_at: nil)
    render json: current_user.tasks
  end

  def update
    render json: task.update_attributes(completed_at: nil, status: 0), status: :ok
  end
end

app/controllers/api/v1/completed_tasks_controller.rb
# frozen_string_literal: true

class Api::V1::CompletedTasksController < Api::ReactAppController
  def index
    current_user.tasks.active.update_all(status: 1, completed_at: Time.now)
    render json: current_user.tasks
  end

  def new
    render json: current_user.tasks.completed.delete_all, status: :ok
  end

  def update
    render json: task.update_attributes(completed_at: Time.now, status: 1), status: :ok
  end
end

app/controllers/api/v1/tasks_controller.rb
# frozen_string_literal: true

class Api::V1::TasksController < Api::ReactAppController
  def index
    tasks = current_user.tasks.by_status(params[:status]).order(:sort)
    render json: tasks
  end

  def create
    render json: current_user.tasks.create(task_params)
  end

  def update
    render json: task.update(title: params[:title]), status: :ok
  end

  def destroy
    render json: task.destroy
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def task
    current_user.tasks.find(params[:id])
  end

  def task_params
    params.require(:task).permit(%i[title completed_to])
  end
end

app/controllers/completed_task_controller.rb
class CompletedTaskController < ApplicationController
  def index
    Task.active.update_all(status: 1, completed_at: Time.now)
    @tasks = Task.all.order(:sort)
    respond_to do |format|
      format.js
    end
  end

  def new
    Task.completed.delete_all
    respond_to do |format|
      format.js
    end
  end

  def update
    task.update_attributes(completed_at: Time.now, status: 1)
  end

  private

  def task
    Task.find(params[:id])
  end
end

app/controllers/completed_tasks_controller.rb
# frozen_string_literal: true

class CompletedTasksController < ApplicationController
  def index
    current_user.tasks.active.update_all(status: 1, completed_at: Time.now)
    @tasks = current_user.tasks.order(:sort)
    respond_to do |format|
      format.js
    end
  end

  def new
    current_user.tasks.completed.delete_all
    respond_to do |format|
      format.js
    end
  end

  def update
    task.update_attributes(completed_at: Time.now, status: 1)
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  def index
    @task = Task.new
    @tasks = current_user.tasks.by_status(params[:status]).order(:sort)
    @active_counte = current_user.tasks.active.count
  end

  def create
    @task = current_user.tasks.create(task_params)
    respond_to do |format|
      format.js
    end
  end

  def update
    task.update(title: params[:title])
  end

  def destroy
    task.destroy
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/todos_controller.rb
# frozen_string_literal: true

class TodosController < ApplicationController
  layout 'react_app'
end

app/helpers/tasks_helper.rb
# frozen_string_literal: true

module TasksHelper
  def update_status_url(active_count)
    active_count != 0 ? completed_tasks_path : active_tasks_path
  end
end

app/views/active_task/index.js.erb
for(i = 0; i < $('.row-task').length; i++) {
  task.changeNumber('+');
}
$('#container').html("<%= j (render partial: 'tasks/task', locals: { tasks: @tasks } ) %>");
task.checkedAll('<%= completed_task_index_path %>');

app/views/active_tasks/index.js.erb
for(i = 0; i < $('.row-task').length; i++) {
  task.changeNumber('+');
}
$('#container').html("<%= j (render partial: 'tasks/task', locals: { tasks: @tasks } ) %>");
task.checkedAll('<%= completed_tasks_path %>');

app/views/completed_task/index.js.erb
for(i = 0; i < $('#container').find('.active').length; i++) {
  task.changeNumber('-');
}
$('#container').html("<%= j (render partial: 'tasks/task', locals: { tasks: @tasks } ) %>");
task.checkedAll('<%= active_task_index_path %>');

app/views/completed_tasks/index.js.erb
for(i = 0; i < $('#container').find('.active').length; i++) {
  task.changeNumber('-');
}
$('#container').html("<%= j (render partial: 'tasks/task', locals: { tasks: @tasks } ) %>");
task.checkedAll('<%= active_tasks_path %>');

app/views/completed_tasks/new.js.erb
$('.completed').remove();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header class='navbar justify-content-end'>
      <div class='navbar-inner row pad-9'>
        <span class='col-mg-7 pad-rig-20'>Hi, <%= link_to current_user.email, edit_user_registration_path %></span>
        <div class='col-mg-5'>
          <%= link_to '', destroy_user_session_path, data: { confirm: 'Are you sure?' }, method: :delete %>
        </div>
      </div>
    </header>
    <div class='container-fluid'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application'%>
  </head>
  <body>
    <%= yield%>
  </body>
</html>

app/views/layouts/react_app.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class='container-fluid'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_task.html.erb
<% tasks.each do |task| %>
  <div id='<%= task.sortable_id %>' data-task-id='<%= task.id %>' class='row-fluid pt-2 task row-task <%= task.status %>'>
    <div class='col-md-auto col-sm-auto col-auto pr-0'>
      <i class='handle'></i>
      <%= check_box_tag 'status', value = task.status, checked = task.completed?, options = { id: "checked_#{task.id}", class: "checkbox-status-#{task.status}" } %>
      <%= label_tag "checked_#{task.id}", '', class: 'check' %>
    </div>
    <div class="col-md-10 col-sm-10 col-10 p-0 word-break">
      <%= label_tag '', "#{task.title}", class: "completed-action w-100 title-#{task.status}", data: { toggle: 'tooltip', placement: 'top' }, title: "#{task.completed_at&.localtime&.strftime("%e %b %Y %H:%M")}" %>
    </div>
    <div class='col-md-auto col-sm-auto col-auto text-right'>
      <%= link_to '', task_path(task), method: :delete, remote: true,  data: { confirm: 'Are you sure?' }, class: 'action delete-action' %>
    </div>
  </div>
<% end %>

app/views/tasks/clear_completed.js.erb
$('.completed').remove();

app/views/tasks/create.js.erb
$('#input-text').val('');
$('.datepicker').val('');

task.create('<%= @task.id %>', '<%= @task.title %>', '<%= @task.status %>', '<%= task_path(@task) %>');

app/views/tasks/destroy.js.erb
var currentTask = $('[data-task-id="<%= params[:id] %>"]');
currentTask.remove();
if (currentTask.hasClass('active')) {
	task.changeNumber('-');
}

app/views/tasks/index.html.erb
<div class='row-fluid text-center'>
  <div class='text-center h1'>
     <p>todos</p>
  </div>
</div>
<div class='row-fluid content-task pl-0 pr-0'>
  <div class='row-fluid d-flex col-md-12 col-sm-12 col-12 row-create pt-2'>
    <%= link_to '', update_status_url(@active_count), remote: true, class: 'checked-all' %>
    <%= form_for @task, method: :post, remote: true do |f| %>
      <div class='col-md-8 col-sm-8 col-7 border-0'>
        <%= f.text_field :title, placeholder: 'What needs to be done?', class: 'border-0 input-text', autocomplete: 'off', id: 'input-text' %>
      </div>
      <div class='col-md-4 col-sm-4 col-5 pl-0 pr-0'>
        <%= f.text_field :completed_to, class: 'border-0 input-data datepicker', autocomplete: 'off' %>
      </div>
      <%= f.submit class: 'invisible d-none' %>
    <% end %>
  </div>
  <div class='row-fluid col-md-12 col-sm-12 col-12 sortable m-0 p-0' id='container'>
    <%= render partial: 'task', locals: { tasks: @tasks } %>
  </div>
  <div class='row-fluid d-flex w-100 text-center pt-2 m-0'>
    <div class='col-md-3 col-sm-3 col-3'>
      <p class='text-left' id='num'><%= pluralize @active_counte, 'item' %> left</p>
    </div>
    <div class='col-md-6 col-sm-6 col-5'>
      <%= link_to 'all', root_path, 'data-attribute': 'btn-status-', class: 'btn btn-sm disabled', remote: true %>
      <%= link_to 'Active', root_path(@tasks, status: 0), 'data-attribute': 'btn-status-0', class: 'btn btn-sm', remote: true %>
      <%= link_to 'Completed', root_path(@tasks, status: 1), 'data-attribute': 'btn-status-1', class: 'btn btn-sm', remote: true %>
    </div>
    <div class='col-md-3 col-sm-3 col-3 pl-0'>
      <%= link_to 'Clear completed', new_completed_task_path, remote: true, class: 'badge badge-light' %>
    </div>
  </div>
</div>
<div class='row-fluid line1'></div>
<div class='row-fluid line2'></div>

app/views/tasks/index.js.erb
$('.disabled').removeClass('disabled');
var status = '<%= params[:status] %>';
$('#container').html("<%= j (render partial: 'task', locals: { tasks: @tasks } ) %>");
$('[data-attribute="btn-status-' + status + '"]').addClass(' disabled');

app/views/todos/index.html.erb
<%= react_component('Tasks') %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>